### ISSUE TITLE
2 irregularities and proposal

### ISSUE THREAD

**Issue by KITT3000** [jDanek/better-minimap#2] opened 2018-05-25 14:00 UTC
1. You can not hide completely the minimap, even mods to hide the hud can not cope.
2. There is some conflict with the mod "TARDIS TELEPORT", there is no possibility of teleporting after enlarging the minimap (key 9).

In the "crop types" mode, a legend should appear with crops and their colors because now you have to learn all by heart.

**Comment by jDanek** [comment] 2018-05-28 07:48
Intentionally, there is no complete hiding of the minimap. Apparently I am upset that the minimapa disappears. I understand that somebody may require this feature, I will add it there in the next version. I will try to ensure that the minimap is able to work with TARDIS mode. I do not know whether to add crop colors to the minimap, it depends on how much space it takes. And because documentation is so feeble, I can not do what I want, and everything is a system of trial and error.

**Comment by KITT3000** [comment] 2018-05-28 12:31
Unfortunately, it is good to turn off all HUDs to take pictures and that's why I mentioned it. I can provide you with full documentation of the game, but unfortunately only for the 1.3.1.0 version of the game (it can always help), but only in a non-public way.

**Comment by jDanek** [comment] 2018-05-30 03:48
I need a little help, for a new version I want to move the settings to the GUI panel, add the option to enable and disable hiding mininapy, recovery time etc. I have a dev branch, the problem is that I do not load localized texts even if the keys exist. Now there are nonexistent keys, but it does not work even when they are right. What with this?

**Comment by KITT3000** [comment] 2018-05-30 06:29
Add this to eg register.lua, outside functions:
```lua
g_isLoaded = false
if not g_isLoaded then
	for k, v in pairs(g_i18n.texts) do
        g_i18n.globalI18N:setText(k, v)
    end
	g_isLoaded = true
end
```

**Comment by jDanek** [comment] 2018-06-02 22:02
The complete hiding of the minimap can now be set in ConfigGui, which I've done thanks to your code, I've moved the transparency and other settings. I tried to make TARDIS compatibility, but it requires an original game map, but I hide it here. I've been doing it for 2 hours, but I do not know how to do it at the moment.

I'll try to solve the color help in the future. I'm still a beginner and GameAPI does not provide me with information for quick development.

And I'll be happy if you check the translation into Polish, it's the output from Google Translator.

**Comment by KITT3000** [comment] 2018-06-02 22:44
I checked the latest version and I have two issues:
1) There is one mistake in XML files with translations (except CZ, in PL - here I have already corrected it), and now it is like this:
`gui_BM_TOOGLE_HELP`
and it should be like this:
`gui_BM_TOGGLE_HELP`
2) As for the mod of teleportation, from what I see you have the function `hide()` and `show()`, the first one you do not use anywhere and the latter is forcefully activated. In my opinion, it is enough to add the possibility of activating the module in the game (change of state for `self.settings.init`), the only thing missing for the teleportation mode action is `g_currentMission.ingameMap.isVisible == true`, and this is the state you set using the function `hide()`. So just add an additional option `Enable/Disable better minimap` in the help window (F1).

**Comment by jDanek** [comment] 2018-06-02 23:03
1. Fixed
2. I know it requires `g_currentMission.ingameMap.isVisible == true`, But because it did not do what I expected, I removed it. I looked into TARDIS, so I added https://github.com/jDanek/better-minimap/blob/master/src/register.lua#L161
This is `self.settings.init` called only once, due to the initial switching of the minimap
I tried to automatically switch the fullscreen using
```Lua
if g_modIsLoaded ["FS17_TARDIS"] then
self:hide();
end;
```
but I only hide my map and I did not activate the game. I was a little disappointed with it.

**Comment by KITT3000** [comment] 2018-06-02 23:28
It works:
```lua
if g_currentMission.tardisBase.tardisOn ~= nil then
    self:hide();
end;
```

**Comment by jDanek** [comment] 2018-06-02 23:40
Where to place it? It would seem good to disable only fullscreen mode. Since it does not make sense to turn it off whenever Tardis is present, the mod does not have to be there at all ...

**Comment by jDanek** [comment] 2018-06-02 23:53
I wrote one functional solution, it works the way I do it.
```Lua
function BM:update(dt)
    -- activate mod if not activated
    if (not self.settings.init) then
        self.settings.init = true;
        g_currentMission.ingameMap.state = IngameMap.STATE_MINIMAP;
        self:show();
    end ;

    if (g_currentMission.tardisBase.tardisOn ~= nil and self.settings.fullscreen) then
        self:hide();
    else
        g_currentMission.ingameMap.state = IngameMap.STATE_MINIMAP;
        self:show();
    end;
```

**Comment by KITT3000** [comment] 2018-06-03 00:04
Probably you also have errors in LOG, when the teleport mod is not activated?

**Comment by jDanek** [comment] 2018-06-03 00:09
It also occurred to me, and so I closed it in
```Lua
-- TARDIS mod compatibility
    if g_modIsLoaded["FS17_TARDIS"] then
        if (g_currentMission.tardisBase.tardisOn ~= nil and self.settings.fullscreen) then
            self:hide();
        else
            g_currentMission.ingameMap.state = IngameMap.STATE_MINIMAP;
            self:show();
        end;
    end;
```
I'm going to try and check LOG

**Comment by jDanek** [comment] 2018-06-03 00:28
Everything looks fine. When you have time to look at the changelog, you will definitely be able to improve Google translation.

**Closed as completed** 2018-06-03 13:30 UTC
